version: 2.0

references:

  getcache: &getcache
    restore_cache:
      keys:
        - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - npm-packages-{{ .Branch }}-
        - npm-packages-

  install_depends: &install_depends
    run:
      name: Install Dependencies
      command: npm install 

  putcache: &putcache
    save_cache:
      paths:
        - node_modules
      key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}

  container: &container
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/ami-ledger

jobs:

  lint:
    <<: *container
    steps:
      - checkout
      - *getcache
      - *install_depends
      - *putcache
      - run:
          Name: Lint
          command: npm run lint

  prettier:
    <<: *container
    steps:
      - checkout
      - *getcache
      - *install_depends
      - *putcache
      - run:
          name: Prettier
          command: npm run pretty-test

  test:
    <<: *container
    steps:
      - checkout
      - *getcache
      - *install_depends
      - *putcache
      - run:
          name: Jest testing
          command: npm run test
      - store_test_results:
          path: reports/jest
      - run:
          name: Upload to CodeCov.io
          command: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

  test_init:
    docker:
      - image: jimrazmus/awscli
    steps:
      - run: aws ec2 reset-image-attribute --image-id $DUMMY_AMI_ID --attribute launchPermission
      - run: aws ec2 modify-image-attribute --image-id $DUMMY_AMI_ID --launch-permission "Add=[{UserId=$AWS_ACCT_ID}]"

workflows:
  version: 2
  doit:
    jobs:
      - lint
      - prettier
      - test_init:
          context: aws-dev
          requires:
            - lint
            - prettier
      - test:
          context: aws-dev
          requires:
            - test_init
